url: "https://crewcraftserver.net" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Crew Craft Server" # the name of your site, e.g. ACME Corp.

excerpt_separator: <!--more-->

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/images/default-card.svg
      lang: en_US
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /news/:year/:month/:day/:title/